export const SPY_LOCATIONS = [
    { location: "Factory", roles: ["Assembly Line Worker", "Quality Control Inspector", "Production Manager"] },
    { location: "Farm", roles: ["Farmhand", "Agricultural Technician", "Farm Manager"] },
    { location: "Restaurant", roles: ["Chef", "Waiter", "Restaurant Manager"] },
    { location: "Hospital", roles: ["Nurse", "Doctor", "Hospital Administrator"] },
    { location: "School", roles: ["Teacher", "Librarian", "Principal"] },
    { location: "Construction Site", roles: ["Construction Worker", "Site Supervisor", "Safety Officer"] },
    { location: "Office Building", roles: ["Receptionist", "Office Manager", "IT Support"] },
    { location: "Library", roles: ["Librarian", "Research Assistant", "Library Director"] },
    { location: "Grocery Store", roles: ["Cashier", "Stock Clerk", "Store Manager"] },
    { location: "Bank", roles: ["Bank Teller", "Loan Officer", "Branch Manager"] },
    { location: "Garage", roles: ["Mechanic", "Service Advisor", "Garage Manager"] },
    { location: "Hotel", roles: ["Concierge", "Housekeeper", "Hotel Manager"] },
    { location: "Airport", roles: ["Security Officer", "Flight Attendant", "Air Traffic Controller"] },
    { location: "Cinema", roles: ["Ticket Seller", "Projectionist", "Cinema Manager"] },
    { location: "Art Gallery", roles: ["Curator", "Art Handler", "Gallery Assistant"] },
    { location: "Gym", roles: ["Personal Trainer", "Gym Manager", "Fitness Instructor"] },
    { location: "Law Firm", roles: ["Lawyer", "Legal Secretary", "Paralegal"] },
    { location: "Pharmacy", roles: ["Pharmacist", "Pharmacy Technician", "Pharmacy Assistant"] },
    { location: "Fire Station", roles: ["Firefighter", "Fire Chief", "Paramedic"] },
    { location: "Music Studio", roles: ["Sound Engineer", "Producer", "Recording Artist"] },
    { location: "Car Dealership", roles: ["Salesperson", "Finance Manager", "Service Technician"] },
    { location: "Theater", roles: ["Actor", "Director", "Stage Manager"] },
    { location: "University", roles: ["Professor", "Research Assistant", "Dean"] },
    { location: "Zoo", roles: ["Zookeeper", "Veterinarian", "Educational Program Coordinator"] },
    { location: "Coffee Shop", roles: ["Barista", "Café Manager", "Coffee Roaster"] },
    { location: "Tech Startup", roles: ["Software Engineer", "Product Manager", "UX Designer"] },
    { location: "Beach Resort", roles: ["Lifeguard", "Beachfront Manager", "Beach Activities Coordinator"] },
    { location: "Museum", roles: ["Museum Curator", "Museum Educator", "Archivist"] },
    { location: "Bakery", roles: ["Baker", "Pastry Chef", "Cake Decorator"] },
    { location: "Pet Store", roles: ["Pet Groomer", "Pet Trainer", "Store Owner"] },
    { location: "Spa", roles: ["Massage Therapist", "Esthetician", "Spa Director"] },
    { location: "TV Studio", roles: ["TV Host", "Camera Operator", "Production Assistant"] },
    { location: "Dentist's Office", roles: ["Dentist", "Dental Hygienist", "Dental Assistant"] },
    { location: "Fashion Boutique", roles: ["Fashion Designer", "Sales Associate", "Store Owner"] },
    { location: "Cruise Ship", roles: ["Captain", "Cruise Director", "Bartender"] },
    { location: "Art Studio", roles: ["Artist", "Art Instructor", "Art Gallery Owner"] },
    { location: "Bookstore", roles: ["Bookseller", "Bookstore Manager", "Events Coordinator"] },
    { location: "Shipping Port", roles: ["Dockworker", "Harbor Master", "Shipping Coordinator"] },
    { location: "Police Station", roles: ["Police Officer", "Detective", "Police Chief"] },
    { location: "Sports Stadium", roles: ["Athlete", "Sports Commentator", "Stadium Manager"] },
    { location: "Aquarium", roles: ["Aquarist", "Aquarium Educator", "Curator"] },
]

