export const TYPE_CHAR_WORDS = [
    "losblancos",
    "losmerengues",
    "lafabrica",
    "quintadelbuitre",
    "zidanesypavones",
    "decimotercera",
    "santiagobernabeu",
    "florentinoera",
    "galacticosera",
    "castilla",
    "morientes",
    "guti",
    "michel",
    "juanito",
    "hugosanchez",
    "ikercasillas",
    "sergioramos",
    "raulgonzalez",
    "fernandohierro",
    "emiliobutragueno",
    "alfredodistefano",
    "pacogento",
    "zinedinezidane",
    "cristianoronaldo",
    "karimbenzema",
    "lukamodric",
    "ferlandmendy",
    "viniciusjunior",
    "uefasupercupwins",
    "intercontinentalcup",
    "copadelreyvictories",
    "laundecima",
    "elclasico",
    "madridderby",
    "mcfoundation",
    "santicazorla",
    "nocheviejamadridista",
    "halamadridynadamas",
    "valdebebas",
    "europeancup",
    "ballondorwinners",
    "recordtitles",
    "iconiccomebacks",
    "legendarymatches",
    "bernabeunights",
    "whiteballet",
    "donsantiagobernabeu",
    "ultrassur",
    "capitangeneral",
    "laséptima",
    "laoctava",
    "lanovena",
    "losvikingos",
    "mijatovic",
    "redondo",
    "lasaetarubia",
    "zamora",
    "puskasaward",
    "chendo",
    "hectorrial",
    "kopa",
    "santillana",
    "juangomezjuanito",
    "quintadelosmachos",
    "euromadridistas",
    "madridismo",
    "decima",
    "undecima",
    "duodecima",
    "trecedecima",
    "catorcedecima",
    "campeones",
    "reyesdeeuropa",
    "estadioalfredodistefano",
    "copasdeeuropa",
    "remontada",
    "laligatitles",
    "clubdelsiglo",
    "goldenfoot",
    "galacticopolicy",
    "ronaldofenomeno",
    "beckhamcrosses",
    "zidanevolleys",
    "robertocarlosfreekicks",
    "ikersaintcasillas",
    "mourinhoera",
    "anfieldmiracle",
    "classicmatches",
    "footballroyalty"
]
// [
//     "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew", "kiwi", "lemon",
//     "mango", "nectarine", "orange", "papaya", "quince", "raspberry", "strawberry", "tangerine", "ugli", "vanilla",
//     "watermelon", "xigua", "yam", "zucchini", "artichoke", "broccoli", "carrot", "daikon", "eggplant", "fennel",
//     "garlic", "horseradish", "iceberg", "jalapeno", "kale", "lettuce", "mushroom", "nutmeg", "onion", "parsnip",
//     "quinoa", "radish", "spinach", "tomato", "utopia", "vermicelli", "wasabi", "xanthan", "yucca", "zest",
//     "azure", "blue", "cyan", "denim", "emerald", "fuchsia", "gold", "heliotrope", "ivory", "jade",
//     "khaki", "lavender", "magenta", "navy", "ochre", "purple", "quartz", "red", "silver", "turquoise",
//     "umber", "violet", "white", "xanadu", "yellow", "zircon", "alpha", "bravo", "charlie", "delta",
//     "echo", "foxtrot", "golf", "hotel", "india", "juliett", "kilo", "lima", "mike", "november", "oscar",
//     "papa", "quebec", "romeo", "sierra", "tango", "uniform", "victor", "whiskey", "x-ray", "yankee", "zulu"
// ];