export const TYPE_CHAR_WORDS = [
    "Blancos",
  "Merengues",
  "Fabrica",
  "Buitre",
  "Zidane",
  "Decima3",
  "Bernabeu",
  "Florentino",
  "Galacticos",
  "Castilla",
  "Morientes",
  "Guti",
  "Michel",
  "Juanito",
  "Hugo",
  "Casillas",
  "Ramos",
  "Raul",
  "Hierro",
  "Butragueno",
  "DiStefano",
  "Gento",
  "Zizou",
  "Cristiano",
  "Benzema",
  "Modric",
  "Mendy",
  "Vinicius",
  "UEFASuper",
  "InterCup",
  "CopaRey",
  "Undecima",
  "Clasico",
  "Derby",
  "Foundation",
  "Cazorla",
  "Nochevieja",
  "HalaMadrid",
  "Valdebebas",
  "EuroCup",
  "BallonWin",
  "Records",
  "Comebacks",
  "Legends",
  "Nights",
  "Ballet",
  "DonSantiago",
  "Ultras",
  "Capitan",
  "Septima",
  "Octava",
  "Novena",
  "Vikingos",
  "Mijatovic",
  "Redondo",
  "Saeta",
  "Zamora",
  "Puskas",
  "Chendo",
  "Rial",
  "Kopa",
  "Santillana",
  "JuanitoG",
  "Machos",
  "EuroFans",
  "Madridismo",
  "Decima",
  "Duodecima",
  "Trece",
  "Catorce",
  "Campeones",
  "Reyes",
  "StefanoStad",
  "Copas",
  "Remontada",
  "Liga",
  "Siglo",
  "Golden",
  "Policy",
  "Fenomeno",
  "Beckham",
  "ZidaneV",
  "CarlosFK",
  "Saint",
  "Mourinho",
  "Anfield",
  "Classics",
  "Royalty",
  "Kroos",
  "Hazard",
  "Courtois",
  "Valverde",
  "Rodrygo",
  "Militao",
  "Alaba",
  "Carvajal",
  "Asensio",
  "Casemiro",
  "Isco",
  "Marcelo",
  "Varane",
  "Figo",
  "Bale",
  "Owen",
  "Ronaldo",
  "Beckham",
  "Khedira",
  "Ozil",
  "Navas",
  "James",
  "Kaka",
  "Ruud",
  "Robben",
  "Sneijder",
  "Alonso",
  "DiMaria"

]
// [
//     "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew", "kiwi", "lemon",
//     "mango", "nectarine", "orange", "papaya", "quince", "raspberry", "strawberry", "tangerine", "ugli", "vanilla",
//     "watermelon", "xigua", "yam", "zucchini", "artichoke", "broccoli", "carrot", "daikon", "eggplant", "fennel",
//     "garlic", "horseradish", "iceberg", "jalapeno", "kale", "lettuce", "mushroom", "nutmeg", "onion", "parsnip",
//     "quinoa", "radish", "spinach", "tomato", "utopia", "vermicelli", "wasabi", "xanthan", "yucca", "zest",
//     "azure", "blue", "cyan", "denim", "emerald", "fuchsia", "gold", "heliotrope", "ivory", "jade",
//     "khaki", "lavender", "magenta", "navy", "ochre", "purple", "quartz", "red", "silver", "turquoise",
//     "umber", "violet", "white", "xanadu", "yellow", "zircon", "alpha", "bravo", "charlie", "delta",
//     "echo", "foxtrot", "golf", "hotel", "india", "juliett", "kilo", "lima", "mike", "november", "oscar",
//     "papa", "quebec", "romeo", "sierra", "tango", "uniform", "victor", "whiskey", "x-ray", "yankee", "zulu"
// ];